DROP TABLE ALLSTARS;
DROP TABLE PLAYERS;
DROP TABLE PLAYERS_TEAMS;
DROP TABLE TEAMS;
DROP PROCEDURE FIX_PLAYER_METRICS;

CREATE TABLE ALLSTARS AS SELECT * FROM XSALES.ALLSTARS;
SELECT * FROM ALLSTARS;

CREATE TABLE PLAYERS AS SELECT * FROM XSALES.PLAYERS;
SELECT * FROM PLAYERS;

CREATE TABLE PLAYERS_TEAMS AS SELECT * FROM XSALES.PLAYERS_TEAMS;
SELECT * FROM PLAYERS_TEAMS;

CREATE TABLE TEAMS AS SELECT * FROM XSALES.TEAMS;
SELECT * FROM TEAMS;

ALTER TABLE PLAYERS
ADD PRIMARY KEY(PLAYERID);

ALTER TABLE ALLSTARS
ADD PRIMARY KEY(YEAR, PLAYERID);

ALTER TABLE TEAMS
ADD PRIMARY KEY(TEAMID, YEAR);

ALTER TABLE ALLSTARS
ADD CONSTRAINT allstarsforeign FOREIGN KEY (PLAYERID) REFERENCES PLAYERS (PLAYERID) ON DELETE CASCADE;

ALTER TABLE PLAYERS_TEAMS
ADD CONSTRAINT play_team_1 FOREIGN KEY (PLAYERID) REFERENCES PLAYERS (PLAYERID) ON DELETE CASCADE;

ALTER TABLE PLAYERS_TEAMS
ADD CONSTRAINT play_team_2 FOREIGN KEY (TEAMID, YEAR) REFERENCES TEAMS (TEAMID, YEAR) ON DELETE CASCADE;

BEGIN
 fix_player_metrics;
END;
/

BEGIN
 FIX_DUPLICATE_PLAYER_STATS;
END;
/
SELECT HEIGHT,WEIGHT FROM PLAYERS;
SELECT
      PLAYERID,
      TEAMID,
      YEAR,
      COUNT(*)
    FROM PLAYERS_TEAMS
    GROUP BY PLAYERID, TEAMID, YEAR
    HAVING count(*) > 1;

